name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      run_tests:
        required: false
        default: true
        type: boolean
    outputs:
      test_result:
        value: ${{ jobs.build.outputs.test_result }}

jobs: 
    build:
        runs-on: ubuntu-latest
        outputs:
          test_result: ${{ steps.run-tests.outputs.test_result }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node_version }}

            - name: Install dependencies
              run: npm install

            - name: Run Tests
              if: ${{ inputs.run_tests }}
              id: test_status
              run: |
               if npm test; then
               echo "result=passed" >> $GITHUB_OUTPUT
               else
               echo "result=failed" >> $GITHUB_OUTPUT
               exit 1
               fi

